
import type { CourseModule, Resource } from '@/types';

export const placeholderModules: CourseModule[] = [
  {
    id: 'module1',
    title: 'Module 1: Payroll Fundamentals & Setup',
    description: 'Understanding the core concepts of payroll, setting up pay schedules, and ensuring accurate employee data management. Introduction to payroll ethics.',
    status: 'completed',
    progress: 100,
    dependencies: [],
    objectives: [
      'Define key payroll terminology (gross pay, net pay, deductions).', 
      'Identify different types of pay periods (weekly, bi-weekly, semi-monthly, monthly).',
      'Understand the importance of accurate W-4 and direct deposit information.',
      'Outline basic payroll record-keeping requirements.',
      'Discuss ethical considerations in payroll processing.',
    ],
    videoUrl: 'https://example.com/video1',
  },
  {
    id: 'module2',
    title: 'Module 2: Wage & Hour Compliance',
    description: 'Exploring FLSA requirements, overtime calculations, minimum wage, and differentiating between exempt and non-exempt employees.',
    status: 'completed',
    progress: 100,
    dependencies: ['module1'],
    objectives: [
      'Explain the Fair Labor Standards Act (FLSA) basics.',
      'Accurately calculate overtime pay (regular rate of pay, 1.5x rule).',
      'Distinguish between exempt and non-exempt employee classifications.',
      'Understand federal and state minimum wage laws.',
      'Identify common wage and hour pitfalls.',
    ],
  },
  {
    id: 'module3',
    title: 'Module 3: Payroll Software & Systems',
    description: 'Evaluating and utilizing various payroll software solutions. Includes hands-on simulation of basic payroll processing.',
    status: 'in-progress',
    progress: 75,
    dependencies: ['module1', 'module2'],
    objectives: [
      'Compare features of popular payroll software (e.g., Gusto, ADP, Paychex).', 
      'Select appropriate payroll system based on company size and needs.',
      'Input employee data and run a mock payroll (simulation).',
      'Understand data security aspects of payroll systems.',
      'Explore integrations with accounting and HR software.',
    ],
  },
  {
    id: 'module4',
    title: 'Module 4: Taxation & Compliance I (Federal)',
    description: 'Deep dive into federal payroll taxes (FIT, FICA). Understanding tax forms and deposit requirements.',
    status: 'in-progress',
    progress: 40,
    dependencies: ['module1', 'module2'],
    objectives: [
      'Calculate Federal Income Tax (FIT) withholding using tax tables and W-4.', 
      'Understand FICA taxes (Social Security & Medicare) - employee and employer portions.',
      'Explain Federal Unemployment Tax Act (FUTA) requirements.',
      'Identify key IRS forms (941, 940, W-2, W-3).',
      'Learn about EFTPS and tax deposit schedules.',
    ],
  },
  {
    id: 'module5',
    title: 'Module 5: Taxation & Compliance II (State & Local)',
    description: 'Navigating state income taxes (SIT) and State Unemployment Tax Act (SUTA). Addressing local tax considerations.',
    status: 'not-started',
    progress: 0,
    dependencies: ['module4'],
    objectives: [
      'Calculate State Income Tax (SIT) withholdings for various states.',
      'Understand State Unemployment Tax Act (SUTA) contributions.',
      'Research and apply local payroll tax ordinances (if applicable).',
      'Discuss multi-state payroll complexities.',
      'Review state-specific new hire reporting.',
    ],
  },
  {
    id: 'module6',
    title: 'Module 6: Benefits & Deductions Administration',
    description: 'Managing employee benefits (health, retirement) and various pre-tax/post-tax deductions, including wage garnishments.',
    status: 'not-started',
    progress: 0,
    dependencies: ['module1', 'module4'],
    objectives: [
      'Differentiate between pre-tax and post-tax deductions.',
      'Administer common benefits (health insurance, 401(k), FSA, HSA).', 
      'Process voluntary and involuntary deductions (e.g., union dues, child support).',
      'Understand rules for wage garnishments.',
      'Calculate net pay accurately with all deductions.',
    ],
  },
  {
    id: 'module7',
    title: 'Module 7: Payroll Reporting, Reconciliation & Auditing',
    description: 'Covering month-end, quarter-end, and year-end reporting. Includes payroll reconciliation techniques and preparing for audits.',
    status: 'not-started',
    progress: 0,
    dependencies: ['module3', 'module4', 'module5', 'module6'],
    objectives: [
      'Perform payroll account reconciliation.',
      'Prepare and file quarterly (Form 941) and annual (Form 940, W-2s, W-3) reports.',
      'Understand year-end close procedures.',
      'Generate internal payroll reports for management.',
      'Prepare for internal and external payroll audits.',
    ],
  },
  {
    id: 'module8',
    title: 'Module 8: Advanced Topics & Real-World Scenarios',
    description: 'Tackling complex payroll situations, fraud prevention, and international payroll considerations. Includes interactive scenarios.',
    status: 'not-started',
    progress: 0,
    dependencies: ['module7'],
    objectives: [
      'Analyze and resolve complex payroll discrepancies.',
      'Identify potential payroll fraud schemes (e.g., ghost employees, falsified hours).',
      'Discuss basic concepts of international payroll (expatriates, local compliance).',
      'Participate in scenario-based decision making for ethical dilemmas.',
      'Stay updated on payroll legislation changes.',
    ],
  },
];

export const placeholderResources: Resource[] = [
  {
    id: 'res1',
    title: 'Payroll Compliance Checklist (Annual)',
    type: 'checklist',
    url: '/resources/payroll-compliance-checklist.pdf',
    iconName: 'CheckSquare',
    description: 'A comprehensive checklist for ensuring annual payroll compliance.',
    moduleAffiliation: 'module7',
    tags: ['compliance', 'checklist', 'annual'],
  },
  {
    id: 'res2',
    title: 'Federal Tax Calculator & W-4 Guide',
    type: 'calculator',
    url: 'https://www.irs.gov/individuals/tax-withholding-estimator',
    iconName: 'Calculator',
    description: 'Link to IRS tool and guide for understanding W-4 and federal tax withholding.',
    moduleAffiliation: 'module4',
    tags: ['taxation', 'calculator', 'federal', 'irs'],
  },
  {
    id: 'res3',
    title: 'Understanding Benefits: Pre-tax vs. Post-tax Video',
    type: 'video',
    url: 'https://example.com/benefits-video-explainer',
    iconName: 'Video',
    description: 'A video explaining the difference between pre-tax and post-tax benefit deductions.',
    moduleAffiliation: 'module6',
    tags: ['benefits', 'video', 'deductions'],
  },
  {
    id: 'res4',
    title: 'Year-End Payroll Reporting Timeline (Template)',
    type: 'template', 
    url: '/resources/year-end-timeline.xlsx',
    iconName: 'GanttChartSquare',
    description: 'A downloadable timeline template for planning year-end payroll reporting activities.',
    moduleAffiliation: 'module7',
    tags: ['reporting', 'template', 'timeline', 'year-end'],
  },
  {
    id: 'res5',
    title: 'IRS Publication 15 (Circular E), Employer\'s Tax Guide',
    type: 'pdf', 
    url: 'https://www.irs.gov/pub/irs-pdf/p15.pdf',
    iconName: 'FileText',
    description: 'Official IRS guide for employers on federal tax responsibilities.',
    moduleAffiliation: 'module4',
    tags: ['external', 'irs', 'link', 'federal tax'],
  },
   {
    id: 'res6',
    title: 'Employee Data Management Best Practices',
    type: 'document', 
    url: '/resources/employee-data-management.pdf',
    iconName: 'FileText',
    description: 'Detailed document on managing employee information securely and effectively.',
    moduleAffiliation: 'module1',
    tags: ['employee data', 'pdf', 'best practices'],
  },
  {
    id: 'res7',
    title: 'Payroll Software Vendor Comparison Matrix (Template)',
    type: 'matrix',
    url: '/resources/payroll-software-matrix.xlsx',
    iconName: 'Table2', 
    description: 'A template to compare features and pricing of payroll software vendors.',
    moduleAffiliation: 'module3',
    tags: ['software', 'vendor', 'matrix', 'template', 'evaluation'],
  },
  {
    id: 'res8',
    title: 'Overtime Calculation Worksheets (FLSA)',
    type: 'worksheet',
    url: '/resources/overtime-worksheets.xlsx',
    iconName: 'FileSpreadsheet',
    description: 'Downloadable worksheets for calculating overtime based on FLSA guidelines.',
    moduleAffiliation: 'module2',
    tags: ['flsa', 'overtime', 'worksheet', 'template', 'calculation'],
  },
  {
    id: 'res9',
    title: 'Payroll Audit Preparation Templates Pack',
    type: 'template',
    url: '/resources/payroll-audit-templates.zip',
    iconName: 'ClipboardCheck',
    description: 'A collection of templates to help prepare for internal or external payroll audits.',
    moduleAffiliation: 'module7',
    tags: ['audit', 'template', 'reporting', 'preparation'],
  },
  {
    id: 'res10', // old res7, new res10
    title: 'Payroll Software Evaluation Guide', // changed title for clarity
    type: 'document', // Changed type
    url: '/resources/software-evaluation-guide.pdf', // Changed URL
    iconName: 'Rows3', // Kept icon, could be FileSearch
    description: 'A comprehensive guide on key criteria for evaluating payroll software.',
    moduleAffiliation: 'module3',
    tags: ['software', 'evaluation', 'guide'],
  },
  {
    id: 'res11',
    title: 'Interactive Scenario: Philly Cheesesteak Fraud Case',
    type: 'interactive-scenario',
    url: '#moodle-link-to-fraud-scenario', // Placeholder link
    iconName: 'MousePointerClick', // New icon needed
    description: 'Engage in a branching scenario based on a real-world payroll fraud case. (Hosted in Moodle)',
    moduleAffiliation: 'module8',
    tags: ['interactive', 'fraud', 'scenario', 'ethics'],
  },
  {
    id: 'res12',
    title: 'Knowledge Check: Payroll Fundamentals Quiz',
    type: 'link', // Links to a Moodle quiz
    url: '#moodle-link-to-fundamentals-quiz', // Placeholder link
    iconName: 'HelpCircle',
    description: 'Test your understanding of basic payroll concepts. (Hosted in Moodle)',
    moduleAffiliation: 'module1',
    tags: ['quiz', 'knowledge check', 'fundamentals'],
  },
  {
    id: 'res13',
    title: 'Simulation: Step-by-Step Payroll Processing',
    type: 'simulation',
    url: '#moodle-link-to-payroll-simulation', // Placeholder link
    iconName: 'PlaySquare', // New icon needed
    description: 'A guided, interactive walkthrough of a typical payroll processing cycle. (Hosted in Moodle)',
    moduleAffiliation: 'module3',
    tags: ['simulation', 'payroll processing', 'interactive', 'walkthrough'],
  },
  {
    id: 'res14',
    title: 'State Payroll Resources (DOL)',
    type: 'link',
    url: 'https://www.dol.gov/agencies/whd/state-data',
    iconName: 'Map',
    description: 'Links to Department of Labor resources for state-specific payroll laws.',
    moduleAffiliation: 'module5',
    tags: ['state laws', 'compliance', 'dol'],
  },
  {
    id: 'res15',
    title: 'Ethics in Payroll Management',
    type: 'document',
    url: '/resources/ethics-in-payroll.pdf',
    iconName: 'ShieldCheck',
    description: 'A document outlining ethical guidelines and best practices for payroll professionals.',
    moduleAffiliation: 'module1',
    tags: ['ethics', 'professionalism', 'compliance'],
  }
];
